### ISSUE TITLE
[BUG] odoo-instance: when trying to run restart command 

### ISSUE THREAD

**Issue by deivislaya** [vauxoo-dev/gist-vauxoo#56]
this error happend when trying to use odoo-instance
I run the odoo-instance script inside the gist-vauxoo folder and fails.

> NOTE: If i run odoo-instance/install script and then run odoo-instance from the root folder this error do not happend.

Here a copy of the error

```bash
[root@9f9187d4c61f]~/tools/gist-vauxoo/odoo-instance$
 (master)$ python odoo-instance restart
Traceback (most recent call last):
  File "odoo-instance", line 449, in <module>
    main()
  File "odoo-instance", line 444, in main
    obj = OerpInstance()
  File "odoo-instance", line 33, in __init__
    self.set_repos()
  File "odoo-instance", line 176, in set_repos
    for config_file in os.listdir(config_dir):
OSError: [Errno 2] No such file or directory: ''
```

Best Regards

**Comment by deivislaya** [comment]
@zaoral please can you help me with this bug
